"""Add item.price, item.options, user.password

Revision ID: aaefd94b999b
Revises: fa30e8eaaac0
Create Date: 2022-03-16 13:45:55.388057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaefd94b999b'
down_revision = 'fa30e8eaaac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.Numeric(), nullable=False))
    op.add_column('item', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order_line', sa.Column('price', sa.Numeric(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('order_line', 'price')
    op.drop_column('item', 'options')
    op.drop_column('item', 'price')
    # ### end Alembic commands ###
